apiVersion: v1
kind: Pod
metadata:
  name: relayer-engine-repo-2
  namespace: default
spec:
  containers:
  - image: joehowarth/relayer-engine
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 1000m
        memory: 600Mi
      limits:
        cpu: 1000m
        memory: 2000Mi
    name: relayer-engine
  restartPolicy: Always